### ISSUE TITLE
Avoiding over-fitting

### ISSUE THREAD

**Issue by Mlahoud** [milutter/deep_lagrangian_networks#3]
Hello, thank you for your interesting work and for sharing the code and the paper.
I just wanted to ask if you evaluated k-folds or other techniques to prevent over-fitting?
Thank you!

**Comment by milutter** [comment]
We did not explicitly evaluate k-folds. However, Figure 5 in https://arxiv.org/pdf/1907.04490.pdf shows the average over multiple seeds. In this specific case, the seed also determines the character assignment between train and test set, which is comparable to a k-fold evaluation.
